# Generated by Django 5.2.6 on 2025-10-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_rating_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'Кино', 'verbose_name_plural': 'Кино'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
    ]
