# Generated by Django 5.2.6 on 2025-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_movie_options_remove_movie_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Отклонено', 'Отклонено'), ('Подтверждено', 'Подтверждено')], default='В обработке', verbose_name='Статус'),
        ),
    ]
