# Generated by Django 5.2.6 on 2025-10-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.FileField(blank=True, help_text='Файл с биографией (.txt)', null=True, upload_to='files/biographies/', verbose_name='Биография'),
        ),
    ]
