# Generated by Django 5.2.6 on 2025-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_movie_trailer_url_alter_person_biography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['name'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(choices=[('актер', 'актер'), ('режиссер', 'режиссер')], default='актер', max_length=200, verbose_name='Профессия'),
        ),
    ]
