# Generated by Django 5.2.6 on 2025-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_profession_options_alter_profession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото личности', null=True, upload_to='images/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Фильм', 'Фильм'), ('Сериал', 'Сериал')], default='Фильм', max_length=200, null=True, verbose_name='Тип'),
        ),
    ]
